import type { Asset, Subscription, UserProfile } from "./types";

export const profile: UserProfile = {
  name: "重启者 01",
  city: "湖北 · 武汉",
  availableCapital: 5000,
  livingReserve: 8200,
  debtRepaymentFund: 2360,
  monthlyNewCapital: 800,
  monthlyAssetProfit: 1260,
  searchRadius: 100,
  skills: ["木工", "家具安装", "电动工具维修"],
  preferredAssetTypes: ["机器设备", "电动工具", "商用设备", "库存"],
  preferredStrategy: "hybrid",
  maxSingleExposure: 4500,
  storageAvailable: true,
  vehicleAvailable: false,
};

const baseCosts = {
  transportKnown: {
    id: "transport-known",
    feeName: "同城运输",
    minAmount: 260,
    maxAmount: 320,
    status: "known" as const,
    evidenceText: "模拟询价：4.2 米货车单程含装车等待",
    evidenceSource: "人工询价记录（模拟）",
    confidence: 0.9,
  },
  platformEstimated: {
    id: "platform-estimated",
    feeName: "平台服务费",
    minAmount: 60,
    maxAmount: 120,
    status: "estimated" as const,
    evidenceText: "公告未列明，按同类标的区间预估",
    evidenceSource: "费用规则模板",
    confidence: 0.62,
  },
  repairUnknown: {
    id: "repair-unknown",
    feeName: "缺件与维修",
    minAmount: null,
    maxAmount: null,
    status: "unknown" as const,
    evidenceText: "公告注明现状交付，未提供通电测试记录",
    evidenceSource: "模拟公告第 6 条",
    confidence: null,
  },
};

export const mockAssets: Asset[] = [
  {
    id: "woodworking-set-001",
    sourcePlatform: "阿里捡漏（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-ALI-001",
    title: "木工修边机、台锯及集尘设备一批",
    category: "机器设备",
    subcategory: "木工设备",
    province: "湖北",
    city: "武汉",
    district: "江夏区",
    seller: "某设备处置方（模拟）",
    auctionStage: "二拍",
    status: "竞价中",
    startTime: "2026-09-20T10:00:00+08:00",
    endTime: "2026-09-24T10:00:00+08:00",
    appraisalPrice: 7800,
    startPrice: 2800,
    currentPrice: 3200,
    deposit: 500,
    bidIncrement: 100,
    distanceKm: 34,
    matchedSkills: ["木工", "家具安装", "电动工具维修"],
    watchlisted: true,
    changeNote: "当前价下降 400 元后重新上拍",
    summary: "技能高度匹配，安全空间尚可；成交前必须核验台锯电机与缺件情况。",
    opportunity: {
      conservativeResaleValue: 5500,
      allInCostMin: 3720,
      allInCostMax: 4200,
      safeMargin: 1300,
      safeRoi: 0.31,
      maxRecommendedBid: 3600,
      minimumCashRequired: 4200,
      capitalFitScore: 96,
      liquidityScore: 78,
      skillFitScore: 94,
      productionScore: 91,
      costCertaintyScore: 72,
      distanceScore: 88,
      overallScore: 74.99,
      grade: "B",
      estimatedMonthlyIncome: 1800,
      paybackMonths: 2.3,
      recommendedUse: "优先自用生产，闲置时再转卖",
      unknownCostCount: 1,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      { ...baseCosts.transportKnown },
      {
        id: "dismantle-estimated",
        feeName: "拆装人工",
        minAmount: 200,
        maxAmount: 500,
        status: "estimated",
        evidenceText: "需买受人自行拆卸，按 2 人半天估算",
        evidenceSource: "模拟公告与费用模板",
        confidence: 0.68,
      },
      { ...baseCosts.platformEstimated },
      { ...baseCosts.repairUnknown },
    ],
    comparables: [
      {
        id: "comp-001",
        title: "同品牌修边机与台锯组合",
        price: 5900,
        region: "武汉",
        condition: "八成新，可试机",
        status: "listing",
        note: "挂牌 18 天，议价空间约 8%（模拟）",
      },
      {
        id: "comp-002",
        title: "小型木工设备组合",
        price: 5300,
        region: "孝感",
        condition: "正常使用，有缺漆",
        status: "sold",
        note: "30 天内成交记录（模拟）",
      },
      {
        id: "comp-003",
        title: "台锯及集尘器两件套",
        price: 5680,
        region: "黄冈",
        condition: "七成新",
        status: "listing",
        note: "不含运输（模拟）",
      },
    ],
    evidence: [
      "公告写明：标的按现状交付，买受人自行拆卸、搬运。",
      "图片可见主要设备 4 件，配件箱数量无法从照片确认。",
      "处置方说明可预约看样，但未提供完整通电视频。",
    ],
    pendingChecks: [
      "现场通电测试台锯与集尘器",
      "核对刀具、导轨、集尘管等配件清单",
      "确认货车能否进入仓库装货区",
    ],
  },
  {
    id: "power-tools-002",
    sourcePlatform: "光谷产权（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-OVU-002",
    title: "锂电冲击钻与角磨机 18 件",
    category: "工具",
    subcategory: "电动工具",
    province: "湖北",
    city: "鄂州",
    district: "华容区",
    seller: "某工程公司（模拟）",
    auctionStage: "清仓",
    status: "即将开始",
    startTime: "2026-09-25T09:00:00+08:00",
    endTime: "2026-09-27T09:00:00+08:00",
    appraisalPrice: 6800,
    startPrice: 2100,
    currentPrice: 2100,
    deposit: 400,
    bidIncrement: 100,
    distanceKm: 61,
    matchedSkills: ["电动工具维修"],
    watchlisted: true,
    changeNote: "新增电池损耗说明",
    summary: "小额且容易拆分出售，但电池健康度会直接影响真实价值。",
    opportunity: {
      conservativeResaleValue: 4050,
      allInCostMin: 2610,
      allInCostMax: 3150,
      safeMargin: 900,
      safeRoi: 0.29,
      maxRecommendedBid: 2380,
      minimumCashRequired: 3150,
      capitalFitScore: 100,
      liquidityScore: 90,
      skillFitScore: 88,
      productionScore: 74,
      costCertaintyScore: 66,
      distanceScore: 72,
      overallScore: 74.99,
      grade: "B",
      estimatedMonthlyIncome: 900,
      paybackMonths: 3.5,
      recommendedUse: "维修整备后分批转卖",
      unknownCostCount: 1,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      {
        ...baseCosts.transportKnown,
        id: "transport-002",
        minAmount: 180,
        maxAmount: 240,
      },
      {
        id: "battery-estimated",
        feeName: "电池整备",
        minAmount: 240,
        maxAmount: 600,
        status: "estimated",
        evidenceText: "部分电池长期闲置，按 2–4 块维修估算",
        evidenceSource: "模拟附件照片",
        confidence: 0.58,
      },
      { ...baseCosts.repairUnknown, id: "missing-002", feeName: "缺失充电器" },
    ],
    comparables: [
      {
        id: "comp-004",
        title: "同系列锂电工具 12 件",
        price: 3600,
        region: "武汉",
        condition: "可试机",
        status: "sold",
        note: "打包成交（模拟）",
      },
    ],
    evidence: ["清单记录工具 18 件、电池 22 块、充电器 8 个。", "附件说明部分电池长期未充电。"],
    pendingChecks: ["逐块测量电池循环与容量", "核对 18 件工具是否均可启动"],
  },
  {
    id: "commercial-oven-003",
    sourcePlatform: "公拍平台（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-GP-003",
    title: "商用双层烤箱与和面机",
    category: "商用设备",
    subcategory: "餐饮设备",
    province: "湖北",
    city: "武汉",
    district: "硚口区",
    seller: "某餐饮门店（模拟）",
    auctionStage: "一拍",
    status: "竞价中",
    startTime: "2026-09-21T10:00:00+08:00",
    endTime: "2026-09-23T15:00:00+08:00",
    appraisalPrice: 9600,
    startPrice: 3800,
    currentPrice: 4200,
    deposit: 1000,
    bidIncrement: 200,
    distanceKm: 12,
    matchedSkills: [],
    summary: "距离近、变现参照充分，但缺少餐饮技能且三相电改造费用不确定。",
    opportunity: {
      conservativeResaleValue: 6300,
      allInCostMin: 4920,
      allInCostMax: 6150,
      safeMargin: 150,
      safeRoi: 0.024,
      maxRecommendedBid: 3950,
      minimumCashRequired: 6150,
      capitalFitScore: 42,
      liquidityScore: 72,
      skillFitScore: 18,
      productionScore: 60,
      costCertaintyScore: 51,
      distanceScore: 96,
      overallScore: 49,
      grade: "C",
      estimatedMonthlyIncome: 0,
      paybackMonths: 0,
      recommendedUse: "不符合当前本金条件，继续观察",
      unknownCostCount: 1,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      { ...baseCosts.transportKnown, id: "transport-003", minAmount: 350, maxAmount: 450 },
      {
        id: "electric-003",
        feeName: "三相电改造",
        minAmount: 300,
        maxAmount: 900,
        status: "estimated",
        evidenceText: "现场接口与用户场地不一致",
        evidenceSource: "设备铭牌（模拟）",
        confidence: 0.55,
      },
      { ...baseCosts.repairUnknown, id: "repair-003", feeName: "加热管维修" },
    ],
    comparables: [
      {
        id: "comp-005",
        title: "双层烤箱与和面机组合",
        price: 6800,
        region: "武汉",
        condition: "正常使用",
        status: "listing",
        note: "商家报价（模拟）",
      },
    ],
    evidence: ["铭牌显示设备需要 380V 电源。", "公告只说明设备可启动，未记录满载测试。"],
    pendingChecks: ["确认烤箱升温速度与温控", "询问拆卸时是否需要燃气专业人员"],
  },
  {
    id: "office-laptops-004",
    sourcePlatform: "破产资产（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-PC-004",
    title: "办公笔记本电脑 10 台",
    category: "电脑",
    subcategory: "办公电脑",
    province: "湖北",
    city: "武汉",
    district: "洪山区",
    seller: "某清算管理人（模拟）",
    auctionStage: "变卖",
    status: "待核验",
    startTime: "2026-09-22T09:00:00+08:00",
    endTime: "2026-09-29T17:00:00+08:00",
    appraisalPrice: 11800,
    startPrice: 5600,
    currentPrice: 5600,
    deposit: 1200,
    bidIncrement: 200,
    distanceKm: 8,
    matchedSkills: [],
    summary: "总价超出当前资产本金，且硬盘与电池状态未知，暂不纳入候选。",
    opportunity: {
      conservativeResaleValue: 7600,
      allInCostMin: 6500,
      allInCostMax: 8200,
      safeMargin: -600,
      safeRoi: -0.073,
      maxRecommendedBid: 4650,
      minimumCashRequired: 8200,
      capitalFitScore: 20,
      liquidityScore: 86,
      skillFitScore: 12,
      productionScore: 35,
      costCertaintyScore: 38,
      distanceScore: 98,
      overallScore: 38,
      grade: "Skip",
      estimatedMonthlyIncome: 0,
      paybackMonths: 0,
      recommendedUse: "跳过：超预算且未知维修费用过多",
      unknownCostCount: 1,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      { ...baseCosts.transportKnown, id: "transport-004", minAmount: 80, maxAmount: 120 },
      {
        ...baseCosts.repairUnknown,
        id: "battery-004",
        feeName: "电池与键盘维修",
      },
      {
        id: "data-004",
        feeName: "数据清除与系统安装",
        minAmount: 400,
        maxAmount: 700,
        status: "estimated",
        evidenceText: "硬盘按清算要求需清除",
        evidenceSource: "模拟处置说明",
        confidence: 0.75,
      },
    ],
    comparables: [
      {
        id: "comp-006",
        title: "同代办公本 8 台",
        price: 6400,
        region: "武汉",
        condition: "已整备",
        status: "sold",
        note: "批量成交（模拟）",
      },
    ],
    evidence: ["设备清单仅记录型号与数量。", "未附硬盘、电池循环、屏幕亮点检测报告。"],
    pendingChecks: ["逐台进入 BIOS 核对配置", "确认硬盘是否随标的交付", "检查屏幕与电池"],
  },
  {
    id: "hardware-stock-005",
    sourcePlatform: "阿里捡漏（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-ALI-005",
    title: "家具五金连接件库存约 48 箱",
    category: "库存",
    subcategory: "五金耗材",
    province: "湖北",
    city: "孝感",
    district: "孝南区",
    seller: "某家具厂（模拟）",
    auctionStage: "二拍",
    status: "竞价中",
    startTime: "2026-09-19T10:00:00+08:00",
    endTime: "2026-09-26T10:00:00+08:00",
    appraisalPrice: 9200,
    startPrice: 2400,
    currentPrice: 2600,
    deposit: 500,
    bidIncrement: 100,
    distanceKm: 79,
    matchedSkills: ["木工", "家具安装"],
    watchlisted: true,
    changeNote: "二拍起拍价下调 900 元",
    summary: "可用于现有木工订单并拆零销售，但必须抽样核对规格与锈蚀。",
    opportunity: {
      conservativeResaleValue: 5100,
      allInCostMin: 3250,
      allInCostMax: 3900,
      safeMargin: 1200,
      safeRoi: 0.308,
      maxRecommendedBid: 3000,
      minimumCashRequired: 3900,
      capitalFitScore: 98,
      liquidityScore: 66,
      skillFitScore: 92,
      productionScore: 84,
      costCertaintyScore: 70,
      distanceScore: 62,
      overallScore: 74.99,
      grade: "B",
      estimatedMonthlyIncome: 1100,
      paybackMonths: 3.5,
      recommendedUse: "一部分自用降本，其余拆零转卖",
      unknownCostCount: 1,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      { ...baseCosts.transportKnown, id: "transport-005", minAmount: 320, maxAmount: 420 },
      {
        id: "sorting-005",
        feeName: "分拣与重新包装",
        minAmount: 280,
        maxAmount: 560,
        status: "estimated",
        evidenceText: "原包装标签不完整，按 2 人 1 天估算",
        evidenceSource: "模拟看样记录",
        confidence: 0.71,
      },
      {
        ...baseCosts.repairUnknown,
        id: "damage-005",
        feeName: "锈蚀与报损",
      },
    ],
    comparables: [
      {
        id: "comp-007",
        title: "家具连接件混装库存",
        price: 5400,
        region: "武汉",
        condition: "未拆封为主",
        status: "listing",
        note: "约 45 箱（模拟）",
      },
    ],
    evidence: ["盘点表列明 48 箱，但部分箱体标签无法辨认。", "图片显示仓库地面干燥，无明显泡水痕迹。"],
    pendingChecks: ["随机开箱 5 箱核对规格与数量", "确认是否存在非标或停产规格"],
  },
  {
    id: "used-van-006",
    sourcePlatform: "公拍平台（模拟）",
    sourceMode: "mock",
    externalId: "MOCK-GP-006",
    title: "2018 年厢式运输车一辆",
    category: "车辆",
    subcategory: "商用车",
    province: "湖北",
    city: "黄冈",
    district: "黄州区",
    seller: "某物流企业（模拟）",
    auctionStage: "一拍",
    status: "即将开始",
    startTime: "2026-09-28T10:00:00+08:00",
    endTime: "2026-09-30T10:00:00+08:00",
    appraisalPrice: 36000,
    startPrice: 21800,
    currentPrice: 21800,
    deposit: 5000,
    bidIncrement: 500,
    distanceKm: 94,
    matchedSkills: [],
    summary: "保证金已等于全部资产本金，明显不符合当前资本等级。",
    opportunity: {
      conservativeResaleValue: 29800,
      allInCostMin: 24800,
      allInCostMax: 32600,
      safeMargin: -2800,
      safeRoi: -0.086,
      maxRecommendedBid: 19000,
      minimumCashRequired: 32600,
      capitalFitScore: 0,
      liquidityScore: 70,
      skillFitScore: 8,
      productionScore: 42,
      costCertaintyScore: 45,
      distanceScore: 55,
      overallScore: 29,
      grade: "Skip",
      estimatedMonthlyIncome: 0,
      paybackMonths: 0,
      recommendedUse: "跳过：远超当前 L2 本金范围",
      unknownCostCount: 2,
      costEstimateComplete: false,
      valuationAvailable: true,
    },
    costs: [
      {
        id: "transfer-006",
        feeName: "过户与检测",
        minAmount: 800,
        maxAmount: 1400,
        status: "estimated",
        evidenceText: "按同类车辆本地办理区间估算",
        evidenceSource: "车辆费用模板",
        confidence: 0.73,
      },
      { ...baseCosts.repairUnknown, id: "repair-006", feeName: "发动机与轮胎维修" },
      { ...baseCosts.repairUnknown, id: "violation-006", feeName: "违章与停车欠费" },
    ],
    comparables: [],
    evidence: ["里程表照片显示约 16.8 万公里。", "公告未明确年检与违章处理责任。"],
    pendingChecks: ["查询车辆违章与抵押状态", "检测发动机、变速箱与轮胎"],
  },
];

export const subscriptions: Subscription[] = [
  {
    id: "sub-001",
    name: "湖北木工生产型机会",
    platforms: ["阿里捡漏", "光谷产权"],
    region: "湖北 · 100 公里",
    budget: 5000,
    categories: ["木工设备", "电动工具"],
    minSafeRoi: 0.2,
    maxUnknownCosts: 2,
    productionFirst: true,
    enabled: true,
    lastMatched: 2,
  },
  {
    id: "sub-002",
    name: "小额库存转卖",
    platforms: ["全部模拟平台"],
    region: "武汉及周边",
    budget: 3000,
    categories: ["五金库存", "小型商用设备"],
    minSafeRoi: 0.25,
    maxUnknownCosts: 1,
    productionFirst: false,
    enabled: true,
    lastMatched: 1,
  },
  {
    id: "sub-003",
    name: "L3 升级观察池",
    platforms: ["阿里捡漏"],
    region: "湖北",
    budget: 10000,
    categories: ["成套设备", "商用设备"],
    minSafeRoi: 0.3,
    maxUnknownCosts: 1,
    productionFirst: true,
    enabled: false,
    lastMatched: 0,
  },
];

export const scanStats = {
  scanned: 8426,
  capitalFit: 376,
  regionFit: 98,
  costPassed: 31,
  comparableReady: 15,
  marginPassed: 6,
  skillMatched: 2,
};

export const capitalLevels = [
  { level: "L0", threshold: 1000, title: "生存观察", focus: "保生活、观察市场、积累本金" },
  { level: "L1", threshold: 3000, title: "工具起步", focus: "小工具、小设备、轻量经营资产" },
  { level: "L2", threshold: 5000, title: "微型周转", focus: "店退设备、小额库存、生产资料" },
  { level: "L3", threshold: 10000, title: "组合交易", focus: "小型机器、批量库存、商用设备" },
  { level: "L4", threshold: 30000, title: "经营扩容", focus: "成套设备、商用车辆、小型清算资产" },
  { level: "L5", threshold: 50000, title: "资产经营", focus: "车辆、工业设备、成套资产" },
  { level: "L6", threshold: 100000, title: "复杂资产", focus: "不动产、工业资产、复杂尽调" },
];

export function findAsset(id: string) {
  return mockAssets.find((asset) => asset.id === id);
}
